# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-08-14 12:06:19.075270 UTC
# Namespace:     nova_dsdl.voltage_regulator

# There are no data types in this namespace. There may be data types in nested namespaces.
