# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-08-14 12:06:18.932885 UTC
# Namespace:     nova_dsdl.motor_driver

# There are no data types in this namespace. There may be data types in nested namespaces.
