# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-08-09 11:43:32.306997 UTC
# Namespace:     nova_dsdl.motor_driver

# There are no data types in this namespace. There may be data types in nested namespaces.
