# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-08-09 11:43:32.429160 UTC
# Namespace:     nova_dsdl.motor_driver.srv

from nova_dsdl.motor_driver.srv.GetPIDConstant_1_0 import GetPIDConstant_1_0 as GetPIDConstant_1_0
from nova_dsdl.motor_driver.srv.SetPIDConstant_1_0 import SetPIDConstant_1_0 as SetPIDConstant_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
GetPIDConstant_1 = GetPIDConstant_1_0
SetPIDConstant_1 = SetPIDConstant_1_0
