# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pih/FYP/nova-can/examples/dsdl/nova_dsdl/motor_driver/srv/GetPIDConstant.1.0.dsdl
#
# Generated at:  2025-08-09 11:43:32.432966 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     nova_dsdl.motor_driver.srv.GetPIDConstant
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class GetPIDConstant_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        P: int = 0
        I: int = 1
        D: int = 2

        def __init__(self,
                     constant: None | int | _np_.uint8 = None) -> None:
            """
            nova_dsdl.motor_driver.srv.GetPIDConstant.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param constant: saturated uint2 constant
            """
            self._constant: int

            self.constant = constant if constant is not None else 0  # type: ignore

        @property
        def constant(self) -> int:
            """
            saturated uint2 constant
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._constant

        @constant.setter
        def constant(self, x: int | _np_.uint8) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 3:
                self._constant = x
            else:
                raise ValueError(f'constant: value {x} is not in [0, 3]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_unsigned(max(min(self.constant, 3), 0), 2)
            _ser_.pad_to_alignment(8)
            assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
                'Bad serialization of nova_dsdl.motor_driver.srv.GetPIDConstant.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> GetPIDConstant_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "constant"
            _f0_ = _des_.fetch_aligned_unsigned(2)
            self = GetPIDConstant_1_0.Request(
                constant=_f0_)
            _des_.pad_to_alignment(8)
            assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
                'Bad deserialization of nova_dsdl.motor_driver.srv.GetPIDConstant.Request.1.0'
            assert isinstance(self, GetPIDConstant_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'constant=%s' % self.constant,
            ])
            return f'nova_dsdl.motor_driver.srv.GetPIDConstant.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 1

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8WHgs(0{@j%T~8B16fNHc6eT4PO^A&ODG#jjV&a1je25_xY+67uF_YQdp?8wqopolmX-!Pzg-9}qCX7%1S?_FH3Me7=rFVAb'
            'o;mm4bLQLVuis;Z{AV7eolu35M--EsM*Iu)Bj%An#HmnRGi&ZPw9EpXNw(ifnLW2FC-$qYm@$&j828r_(V`>=iG>!Dgp#+I^ptFQ'
            'Z<wy_Y;B4}X_{!S&OT>MX={oEPbe-D3k5TA*o)6?b*Nf6wI|k06RNf3ex{kSpYXODcwU^cW^9|YC>-#cA|ch3Xh-^{^i=YgYou#U'
            '=^#<OnXqst(X7ej)nccK&ozly($rw9!w4QwrAaJ8OfC8uk2Ft|H4{yy9Vg6$IWu4D<2y8O6H|6w#<?|<jrIM5`uhIsEqiL~*31#t'
            'qL9k)@=a%%4`Zen^crZ*C<#SiO~K;Ej4AdzdqEURFyD(FREOaqJccJ-kfEA|C0I7&q(!3)Sugfm!rG~1%1z)(LyC2(@f(f$;NY3b'
            'V@U(|6-zB{_hL7<LUqWMp?tinax0acoC<ib)&qtYIQjoU*!l;;@Bo3C(j@^Azth#KLwX9cunH^i3SPoCY-BjvkYNJ?s#$2y%nUi^'
            'Z5EPLNKJTX_slF&B9j5bjfjzy;#|yx`-`}bgRG%X+BNs}9ECFU42J~58Dk{ncyeU>sD{mQCRq(=f+1_uIE_%(X4DM;Aub$b&7I30'
            '!fbSrH4E2#wB|kc^5fb`r$m4%<Rw|6oxWQ<VD>vKnZ-tTQP!f2x-8Q&f|Lhhx}SHY>-7YayH2~6&CFFc*o?lfnOVsDL$n}L2%Y1r'
            'lp-IfSD*p=Z~%w!9zMVke9Xy@5<kLDEceAY5I>fpudk8O2G?)%b%R~V-i#2DT2sCWM0H|cL>!G%+GVjo_dDIbOPQot-oWMKBmj<Y'
            '2q<%}M#GRN&A$#o+wJaUQAB0u`Yw1sY^6H<Q~CJBrCkJDEoMH}8S?}~7tpo~Cfw_hMbz=1aweon{tE78zLT)`2d3yJ{-y;000'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     value: None | int | _np_.uint16 = None) -> None:
            """
            nova_dsdl.motor_driver.srv.GetPIDConstant.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param value: saturated uint16 value
            """
            self._value: int

            self.value = value if value is not None else 0  # type: ignore

        @property
        def value(self) -> int:
            """
            saturated uint16 value
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._value

        @value.setter
        def value(self, x: int | _np_.uint16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._value = x
            else:
                raise ValueError(f'value: value {x} is not in [0, 65535]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u16(max(min(self.value, 65535), 0))
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
                'Bad serialization of nova_dsdl.motor_driver.srv.GetPIDConstant.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> GetPIDConstant_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f1_ holds the value of "value"
            _f1_ = _des_.fetch_aligned_u16()
            self = GetPIDConstant_1_0.Response(
                value=_f1_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
                'Bad deserialization of nova_dsdl.motor_driver.srv.GetPIDConstant.Response.1.0'
            assert isinstance(self, GetPIDConstant_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'value=%s' % self.value,
            ])
            return f'nova_dsdl.motor_driver.srv.GetPIDConstant.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 2

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8WHgs(0{?|m-%k`V5I(}4hoA^KB9Ho@1Rq=hf4n1zAt&dB0}~!h({AgvNw;m<?&Z#eL|zCcO*Fas|2o~{w;}G!PCGN-d^7X)'
            'NBz%Hy;gnUi5XExWriHH0!#576Uj1^>%wR!Jd5FB&)YKhrDX>r!{Ru;IElw`H8haI1^73V9$-{~6xwTxs1*ZdGiL|cN9Mb`+gn;W'
            'kCo5%nKNKR(hPzSC$x&Z7Mfqq?Qv{RwQHyGB!)SJy|;ptp1Jrn-o^7WD2B$4V3J<(n?)3RjC>+}SGuvH5FY5p&^lC3^cADK%CkPR'
            'H=CV9M0g~b>U$pB3jm&D=TV_)YKD|TdZAnl%|7#q6J+wG@VI+{pU|=`NZCsn;~4JuHV+Q>HxE8+$J4kU!xBm(qS(^wmCj1S8=*14'
            'vV=NyM0FlREtUj_*0lj4GMX&oIPzzF(E(k`jAc3YjK-f~9(@x-Mv>9hBSB*)EFz~%n=^1oh75*Up_zVC5Fpou-4DCzb_~r=y@J|Y'
            'r)5tY0g=-?M_p(;E&gSW6_{*@3nO7wp`PXp5SOZm;lXuXKsG2NhUHt@SkKn7D%_`Wv=GM*cv+@=+Sx$lES~Y_d?hSYtxgoGz@6l='
            '`u}?KH|qiCOEt2vT#W#EjjYzbD&P!;k~~}GulO2Y=NtSrf5YGMcNM=nA`+TixscV>&Va4IeFjSJh5uBYdvH9LRhUNF#PIYk5H~7_'
            'mI7AZ+GB+V(Rz3#pAEAZ`nwY6J(P0+(&wG<sEa8Ts{c<A?<H@iloH#~Z7(29B=#$=wikXo0`JpIfMR>5B+zalRMI^dc$kc4(tas%'
            '%AQ4RXt1iDaHk}WlqCBLTiKAbWCQ>J'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'nova_dsdl.motor_driver.srv.GetPIDConstant.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8WHgs(0{@*=Yi}Dx6m?$pHhqxF(1K8@KY>%!g*FmjkdWGjRFP@0>=bBA7-n}Tz9X%7wllNFu2eyVRAMv&L<W8a0`UjAv%7vI'
        '#OlM6<-0pGXU;wMp6ef$|5*1b`Nv#Ihmne6pC~3djrn65#LOq5=%qq&&8#`oVY1IdwmVFjJ+$jj?GxKD=ZIvFGNv@q?mbk@xsH}u'
        's55zN=L$(^4{@$1qEAVFSx;yoNhEonNngpne~0PT_U3JoC`}XXw+m=%Jc2tE7m2%|`b8NZ+U7#D^2|O(a)fFvd5~$Q>>l1WC!fhK'
        'YgV>6i=!#ORT5E6i!|mPPbKehjdZQ4-AfejCM?=cH0v^XG}$vG;F`oN>1wdeMFbBiYSa@E9`%BZ$C@X~nrfG6#|cluTjpYGjPKC='
        '+j!)zJ8@{u>CVmFd+nRMpKjV`wr$Pp#7PuU8O`1_$^uw5URVlf%`%BZXidf9Ld|$%WhX@8O?bPE-f1qv6?hLC1;|3n!c}<RoFaW1'
        'XUO{USQ0i!B~z{fM+EWORO34ukHKNXoZgo-bZ;?LZ>x-5-73ummxc=Pu4~VwvYk_b4fv=8hL5rGFN3go0>a`HftlJ&1Cd}@^r}Nz'
        'hl_9ne7FUlKojm{SlWo803p>ZvLkbz?DGMONGhZzJhD6H0#PE9A;X23k(6RxOx69wJitP>&`*PwdwYnDvhV>G34}AoQp$1X($@VJ'
        'isejlEu;yCY(RTyjD2mET>%hc;vj3z&Uy$>ql>J$bj(NB{SW<oyLPQpBS01Mk}T1#zn!V=0bDhgONZCBsAFH&X&pi8(`H)BRVijd'
        'f`<#IJ(tb-qij%&v9FoAl<PyZAW{gO<ExY+ANaBXU%`EN01x47*n@9ylOw-Of*6%}cifEA=Eqd@@n>Xoi|fzw=MI~+y;&k6wWdA~'
        'L=Ag^h&dXkc9-=8y5IHf=P8pE)0?{d6bXUj41s}ptwp1VC*A*Tf+ucuCyQe$hsRf8<5$~gF8-zh9C2xZV4GeRV4gjmVCVuma6#2g'
        'k1VE+|Ee<~P4X$YlLfAYu@TXgSQy31QCuwvteP7yGja<I3uj>sF6>!&;{<c973Mm~&9zbt2xqV?pwPm!{)FEZv`5g{f!z}-3Eu*R'
        'z||AjL2k_Mt96n$q01nd(=zY~bRqV4@OV;_?<diZGnH7wO2AL90C0dwj_~_4u9;F}Om_W+rJN|(n32#!h-&$dSt>TO`imRha#DeO'
        'nK?ll@HhMg|H41n3#vN8!~3tO>U=4)!2b`3^<=;_2mk;'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
