# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-08-14 12:06:19.085866 UTC
# Namespace:     nova_dsdl.voltage_regulator.msg

from nova_dsdl.voltage_regulator.msg.Command_1_0 import Command_1_0 as Command_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Command_1 = Command_1_0
