# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-08-09 11:43:32.441147 UTC
# Namespace:     nova_dsdl.sensors.msg

from nova_dsdl.sensors.msg.Current_1_0 import Current_1_0 as Current_1_0
from nova_dsdl.sensors.msg.Position_1_0 import Position_1_0 as Position_1_0
from nova_dsdl.sensors.msg.Velocity_1_0 import Velocity_1_0 as Velocity_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Current_1 = Current_1_0
Position_1 = Position_1_0
Velocity_1 = Velocity_1_0
