# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-08-09 11:43:32.307322 UTC
# Namespace:     nova_dsdl.motor_driver.msg

from nova_dsdl.motor_driver.msg.Command_1_0 import Command_1_0 as Command_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Command_1 = Command_1_0
