# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-08-14 12:06:19.075657 UTC
# Namespace:     nova_dsdl.voltage_regulator.srv

from nova_dsdl.voltage_regulator.srv.EnableTelemetry_1_0 import EnableTelemetry_1_0 as EnableTelemetry_1_0
from nova_dsdl.voltage_regulator.srv.GetCurrent_1_0 import GetCurrent_1_0 as GetCurrent_1_0
from nova_dsdl.voltage_regulator.srv.GetVoltage_1_0 import GetVoltage_1_0 as GetVoltage_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
EnableTelemetry_1 = EnableTelemetry_1_0
GetCurrent_1 = GetCurrent_1_0
GetVoltage_1 = GetVoltage_1_0
